# Site settings
title: Giamir Buoncristiani
email: hello@giamir.com
description: > # this means to ignore newlines until "baseurl:"
  Experiences of an Italian software developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://giamir.com" # the base hostname & protocol for your site
twitter_username: giamir
github_username:  giamir
exclude: ['node_modules']
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
